name: run-test

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Run Test
        run: make test
